spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: http://localhost:8010/eureka
server:
  port: 8761
