spring:
  datasource:
      url: jdbc:mysql://localhost:3306/restaurant_details?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      username: root
      password: password
      platform: mysql
  jpa:
      hibernate:
        ddl-auto: update
  application:
    name: restaurant-service
server:
  port: 8012
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka